"""Provides the automod module's configuration data

Attributes:
    BANNED_WORDS (List[str])
"""
from typing import List

# TODO: Consider loading this from DB or a static file in the bot's home/root folder
BANNED_WORDS: List[str] = [
    "end thyself",
    "end urself",
    "end your own life",
    "end yourself",
    "hang self",
    "hang urself",
    "hang yourself",
    "hang youself",
    "jump off a bridge",
    "k y s",
    "keep thyself safe",
    "keep urself safe",
    "keep yourself safe",
    "keep youself safe",
    "kill yourself",
    "kys",
    "off yourself",
    "take your own life",
    "^FAGGOT",
    "^TRANNY",
    "f a g",
    "f ag",
    "fa g",
    "fag",
    "FAG",
    "FAGGOT",
    "flag got",
    "flaggot",
    "fаggot",
    "FАGGOТ",
    "gaF backwards",
    "tranny",
    "*TRANNY*",
    "TRANNY",
    "TRANNУ",
    "trаnny",
    "!f!a!g!",
    "!fag",
    "*fag",
    "fag!",
    "faggot",
    "FAGGOT",
    "f*gg*t",
    "fаg",
    "n*gger",
    "n*gg*r",
    "N*GG*R",
    "nigga",
    "nigger",
    "NIGGER",
    "trannny",
    "tranny",
    "TRANNY",
    "asshat",
    "asshead",
    "asshole",
    "autist",
    "cuck",
    "cunt",
    "dick",
    "dipshit",
    "fuck",
    "fucker",
    "fuckhead",
    "kill myelf",
    "kill self",
    "kill youself",
    "ladyboy",
    "libtard",
    "moron",
    "motherfucker",
    "retard",
    "retardation",
    "retarded",
    "retards",
    "shithole",
    "sperg",
    "suck me",
    "suck me off",
    "suck my dick",
    "whore",
]
